CREATE TABLE IF NOT EXISTS NOBLE_WIN (
    YEAR INTEGER,
    SUBJECT TEXT,
    WINNER TEXT,
    COUNTRY TEXT,
    CATEGORY TEXT
);


INSERT INTO NOBLE_WIN (YEAR,SUBJECT,WINNER,COUNTRY,CATEGORY)VALUES
   ( 1970, 'PHYSICS', 'HANNES ALFVEN', 'SWEDEN', 'SCIENTIST')
   ( 1970, 'PHYSICS', 'LOUIS NEEL', 'FRANCE', 'SCIENTIST')
   ( 1971, 'PHYSICS', 'PAUL', 'FRANCE', 'SCIENTIST')
   ( 1971, 'CHEMISTRY', 'HAMILTON', 'SWEDEN', 'LINGUIST');

   SELECT *
   FROM NOBLE_WIN
   WHERE SUBJECT NOT LIKE 'P%'

